services:
  frontend:
    build:
      context: next
      args:
        backend_api_host: localhost
        backend_api_port: 8999
        backend_socket_host: localhost
        backend_socket_port: 8998
    ports:
      - 3000:3000
    networks:
      - frontend-backend
    depends_on:
      - backend

  backend:
    build:
      context: sockets
      args:
        node_env: development
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - 8998:8998
      - 8999:8999
    depends_on:
      - redis
    networks:
      - frontend-backend
      - backend-redis
    expose: 
      - 8998
      - 8999
  redis:
    restart: always
    image: redis:alpine
    networks:
      - backend-redis
    expose:
      - 6379
networks:
  frontend-backend:
  backend-redis: