services:
  frontend:
    build:
      context: next
    ports:
      - 3000:3000
    networks:
      - frontend-backend
    depends_on:
      - backend

  backend:
    build:
      context: sockets
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - 8998:8998
      - 8999:8999
    depends_on:
      - redis
    networks:
      - frontend-backend
      - backend-redis
    expose: 
      - 8998
      - 8999
  redis:
    restart: always
    build:
      context: redis
    networks:
      - backend-redis
    expose:
      - 6379
networks:
  frontend-backend:
  backend-redis: