apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      name: socket
      port: 8998
      targetPort: 8998
    - protocol: TCP
      name: api
      port: 8999
      targetPort: 8999